name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: git config --global user.email "psobusiak@gmail.com"
    - run: git config --global user.name "psobusiak"
    - run: ./node_modules/.bin/gatsby build --prefix-paths
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
#         deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        personal_token: 8af0d82f1aac73e1e07e1f7d477d71b2ac4209d4
        publish_dir: ./public
      env:
        CI: true
